# scripts/flatten-sync/lib/context.py
"""Generate _CONTEXT.yaml for AI project exports."""

from datetime import datetime, timezone

import yaml


class _BlockDumper(yaml.SafeDumper):
    """YAML dumper that renders multiline strings as block scalars."""

    pass


def _str_representer(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_BlockDumper.add_representer(str, _str_representer)


def generate_manifest(
    profile_name: str,
    profile_path: str,
    included_files: list[tuple[str, str]],
    exclusion_log: dict,
    modifiers: dict,
) -> str:
    """Generate _CONTEXT.yaml content.

    Args:
        profile_name: name of the profile used
        profile_path: relative path to the profile file
        included_files: list of (source_rel_path, flat_name) tuples
        exclusion_log: {mod_name: [rel_paths]} from walk
        modifiers: full modifier library (for notes)

    Returns:
        YAML string ready to write to _CONTEXT.yaml
    """
    # Count totals
    file_count = len(included_files)
    excluded_count = sum(len(files) for files in exclusion_log.values())

    # Build modifiers_applied section (non-silent only)
    modifiers_applied = {}
    for mod_name, excluded_files in sorted(exclusion_log.items()):
        mod_def = modifiers.get(mod_name, {})
        modifiers_applied[mod_name] = {
            "files": len(excluded_files),
            "note": mod_def.get("note", ""),
            "excluded": sorted(excluded_files),
        }

    context = (
        "This is a flat export of a monorepo generated by the flatten\n"
        "export tool. Directory structure is encoded in filenames\n"
        "using -- as the path separator.\n"
        "\n"
        "To decode a filename back to its source path:\n"
        "  extension--components--App.tsx -> extension/components/App.tsx\n"
        "  lambdas--src--shared_layer--shared--db.py -> lambdas/src/shared_layer/shared/db.py\n"
        "\n"
        "Files starting with _ may have originally started with . (dot).\n"
        "Some AI project platforms rename dotfiles on upload:\n"
        "  _gitignore -> .gitignore\n"
        "  _github--workflows--ci.yml -> .github/workflows/ci.yml\n"
        "\n"
        "This export used the profile below. Some files were intentionally\n"
        "excluded. The modifiers_applied section lists what was excluded\n"
        "and why. If you need a file that appears excluded, ask the user\n"
        "to re-export with that modifier removed.\n"
    )

    manifest = {
        "context": context,
        "exported_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "profile": profile_name,
        "profile_config": profile_path,
        "file_count": file_count,
        "excluded_count": excluded_count,
    }

    # Only include modifiers_applied if there are any
    if modifiers_applied:
        manifest["modifiers_applied"] = modifiers_applied

    return yaml.dump(
        manifest,
        Dumper=_BlockDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )
